[plugins]
  [plugins.cri]
    [plugins.cri.containerd]
      snapshotter = "overlayfs"
      [plugins.cri.containerd.default_runtime]
        runtime_type = "io.containerd.runtime.v1.linux"
        runtime_engine = "/var/vcap/packages/runtime-runc/bin/runc"
        runtime_root = ""
      [plugins.cri.containerd.untrusted_workload_runtime]
        runtime_type = "io.containerd.runtime.v1.linux"
        runtime_engine = "/var/vcap/packages/runtime-runc/bin/runsc"
        runtime_root = "/var/vcap/data/k8s/runtime-runc"
      [plugins.cri.containerd.gvisor]
        runtime_type = "io.containerd.runtime.v1.linux"
        runtime_engine = "/var/vcap/packages/runtime-runc/bin/runsc"
        runtime_root = "/var/vcap/data/k8s/runtime-runc"
    [plugins.cri.cni]
      conf_dir = "/var/vcap/jobs/runtime-runc/etc/cni/net.d"
      bin_dir = "/var/vcap/packages/containerd/bin"
