builds:
  998d32bfb52cb08609ea13d480b6d146ee5648ef:
    version: 998d32bfb52cb08609ea13d480b6d146ee5648ef
    blobstore_id: a5d25373-9166-448a-60cd-7718d9db37f9
    sha1: 1eefa46a1ed9cb7237c3642352a3952d77c860a4
  cfff8089825beb20ac7e4405f988b115d27741ed:
    version: cfff8089825beb20ac7e4405f988b115d27741ed
    blobstore_id: 09fca218-21e6-44a7-78d9-f9f16c1e734e
    sha1: 1a433f6d40bdff39eb82063e0ba1aa00fe0c8651
  e830e04d9842b61f49fe5a7a0f6860421357ce4a:
    version: e830e04d9842b61f49fe5a7a0f6860421357ce4a
    blobstore_id: 513fcc06-8a8a-471f-4cd0-2f9b78073aad
    sha1: 6247156c9ddd7df007a204433a3ef274f4393996
  e89a46e6a5e99b9ca5e81766c4c553c39352e9cc:
    version: e89a46e6a5e99b9ca5e81766c4c553c39352e9cc
    blobstore_id: a2a03ebc-c32a-4c86-74ec-3c206b005512
    sha1: 578e4ea37be2014ac1fc00bed41c4333dbe8c77c
format-version: "2"
