name: prodernetes

instance_groups:
  - name:      lb
    instances: 2
    azs:       [z1,z2,z3]
    vm_resources:
      cpu: 2
      ram: 2048
      ephemeral_disk_size: 2048
    stemcell: default
    networks:
      - name: default

    jobs:
      - name: lb
        release: k8s
        properties:
          vrrp:
            id: 240
            ip: ((virtual-ip))

  - name:      control
    instances: 3
    azs:       [z1,z2,z3]
    vm_resources:
      cpu: 2
      ram: 2048
      ephemeral_disk_size: 20_000
    vm_extensions:
      - kubelet
    persistent_disk: 20_000
    stemcell:  default
    networks:
      - name: default

    jobs:
      - name: etcd
        release: k8s
      - name: control
        release: k8s
        properties:
          kubelet:
            instance-groups:
              - node.default
              - control.default
          apiserver:
            additional-sans:
              - 10.245.0.1
              - ((virtual-ip))
          cluster:
            name: prodernetes
          encryption:
            key: ((encryption-key))
          tls:
            ca:
              certificate: ((tls-ca.certificate))
              key:         ((tls-ca.private_key))
            sa:
              certificate: ((tls-sa.certificate))
              key:         ((tls-sa.private_key))
      - name: net-flannel
        release: k8s
      - name: runtime-runc
        release: k8s
        properties:
          cni: flannel
      - name: kubelet
        release: k8s
        properties:
          apiserver: ((virtual-ip))
          master: true

      - name: jumpbox
        release: k8s
      - name: smoke-tests
        release: k8s

  - name:      node
    instances: 5
    azs:       [z1,z2,z3]
    vm_resources:
      cpu: 2
      ram: 2048
      ephemeral_disk_size: 20_000
    vm_extensions:
      - kubelet
    persistent_disk: 20_000
    stemcell:  default
    networks:
      - name: default

    jobs:
      - name: net-flannel
        release: k8s
      - name: runtime-runc
        release: k8s
        properties:
          cni: flannel
      - name: kubelet
        release: k8s
        properties:
          apiserver: ((virtual-ip))
      - name: nfs
        release: k8s

variables:
  - name: virtual-ip

  - name: tls-ca
    type: certificate
    options:
      is_ca: yes
      common_name: ca

  - name: tls-sa
    type: certificate
    options:
      is_ca: yes
      common_name: sa

  - name: encryption-key
    type: password
    options:
      length: 32
      include_special: yes

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
  - alias:   default
    os:      ubuntu-xenial
    version: latest

releases:
  - name:    k8s
    version: latest
