name: tinynetes

instance_groups:
  - name:      k8s
    instances: 1
    azs:       [z1]
    vm_resources:
      cpu: 2
      ram: 2048
      ephemeral_disk_size: 20_000
    persistent_disk: 20_000

    stemcell:  default

    networks:
      - name: default

    jobs:
      - name: etcd
        release: k8s
      - name: control
        release: k8s
        properties:
          cluster:
            name: tinynetes
          networks:
            nodes:    10.200.192.128/26
            pods:     10.200.192.64/26
            services: 10.200.192.0/26
          encryption:
            key: ((encryption-key))
          tls:
            ca:
              certificate: ((tls-ca.certificate))
              key:         ((tls-ca.private_key))
            sa:
              certificate: ((tls-sa.certificate))
              key:         ((tls-sa.private_key))

      - name: runtime-runc
        release: k8s
      - name: kubelet
        release: k8s
      - name: nfs
        release: k8s

      - name: jumpbox
        release: k8s
      - name: smoke-tests
        release: k8s

variables:
  - name: tls-ca
    type: certificate
    options:
      is_ca: yes
      common_name: ca

  - name: tls-sa
    type: certificate
    options:
      is_ca: yes
      common_name: sa

  - name: encryption-key
    type: password
    options:
      length: 32
      include_special: yes

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
  - alias:   default
    os:      ubuntu-xenial
    version: latest

releases:
  - name:    k8s
    version: latest
